FactoryBot.define do
  factory :api_key do
    user
    name { "Test API Key" }
    # key is auto-generated by model

    trait :photos_create do
      scope { "photos:create" }
    end

    trait :expired do
      expires_at { 1.day.ago }
    end

    trait :revoked do
      revoked_at { 1.day.ago }
    end
  end
end
